name: Sync rules for Surge
on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Checkout release 
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir /home/runner/work/surge
        shell: bash

      - name: Checkout surge-rules repo
        uses: actions/checkout@v3
        with:
          repository: Loyalsoldier/surge-rules
          ref: release

      - name: Set Default branch
        run: |
          cp -rf ./* /home/runner/work/surge/
          ls -la
        shell: bash

      - name: Checkout scripts repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Sync rules
        run: |
          rsync -aP --delete /home/runner/work/surge  ./scripts/surge-rules
        shell: bash

      - name: Git commit changes
        run: |
          git add .
          git commit -m "Auto Update By GitHub bot."

      - name: Git push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.REPO_TOKEN }}'
          branch: '${{ github.ref }}'

